# Generated by Django 5.2.15 on 2026-06-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, help_text='Upload project screenshot.', null=True, upload_to='projects/')),
                ('technologies', models.CharField(help_text='Comma-separated list of technologies used (e.g., Django, Python, SQLite)', max_length=250)),
                ('github_link', models.URLField(blank=True, help_text='GitHub repository URL', null=True)),
                ('live_link', models.URLField(blank=True, help_text='Live project demo URL', null=True)),
                ('order', models.IntegerField(default=0, help_text='Sort order (ascending)')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', 'title'],
            },
        ),
    ]
