# Generated by Django 5.2.15 on 2026-06-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(default='University of Management and Technology (UMT)', max_length=200)),
                ('degree', models.CharField(default='Bachelor of Computer Science', max_length=200)),
                ('status', models.CharField(default='Undergraduate', max_length=100)),
                ('start_year', models.IntegerField(default=2022)),
                ('end_year', models.IntegerField(blank=True, help_text='Leave blank if currently pursuing', null=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of key courses or achievements.')),
                ('order', models.IntegerField(default=0, help_text='Sort order (ascending)')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education Records',
                'ordering': ['order', '-start_year'],
            },
        ),
    ]
