# Generated by Django 5.2.15 on 2026-06-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Laiba Tanseer', max_length=100)),
                ('title', models.CharField(default='Computer Science Undergraduate', max_length=150)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='bio/')),
                ('summary', models.TextField(help_text='Professional summary of the user.')),
                ('cv', models.FileField(blank=True, help_text='Upload CV document.', null=True, upload_to='cv/')),
                ('email', models.EmailField(default='laibtanser@gmail.com', max_length=254)),
                ('linkedin', models.CharField(default='laiba-tanseer', help_text='LinkedIn profile username/slug', max_length=100)),
                ('typing_roles', models.TextField(default='Computer Science Student, AI Enthusiast, Backend Developer, Problem Solver', help_text='Comma-separated values for the typing animation effect in the hero section.')),
            ],
            options={
                'verbose_name': 'Biography',
                'verbose_name_plural': 'Biography',
            },
        ),
    ]
