# Generated by Django 5.2.15 on 2026-06-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Personal Projects Experience', max_length=200)),
                ('description', models.TextField(help_text='Detailed text or bullet points explaining projects/academic experience.')),
                ('order', models.IntegerField(default=0, help_text='Sort order (ascending)')),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experience Records',
                'ordering': ['order'],
            },
        ),
    ]
