# Generated by Django 5.2.15 on 2026-06-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('proficiency', models.IntegerField(default=80, help_text='Enter percentage from 0 to 100')),
                ('category', models.CharField(default='Technical', help_text='Category of the skill (e.g. Languages, Frameworks, AI, Databases)', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Sort order (ascending)')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['order', 'name'],
            },
        ),
    ]
